spring.application.name=demo

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/jachwisunbae?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.encoding=UTF-8
spring.flyway.validate-on-migrate=true
spring.flyway.baseline-on-migrate=false
spring.flyway.clean-disabled=true

spring.sql.init.mode=never

logging.level.root=INFO
logging.level.com.jachwisunbae=INFO
logging.level.org.springframework.web=WARN
